package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * BannerType generated by hbm2java
 */
public class BannerType  implements java.io.Serializable {


     private int bannerTypeId;
     private String bannerTypeName;
     private String descriptions;
     private Integer bannerTypePriority;
     private Boolean bannerTypeStatus;
     private Set banners = new HashSet(0);

    public BannerType() {
    }

	
    public BannerType(int bannerTypeId) {
        this.bannerTypeId = bannerTypeId;
    }
    public BannerType(int bannerTypeId, String bannerTypeName, String descriptions, Integer bannerTypePriority, Boolean bannerTypeStatus, Set banners) {
       this.bannerTypeId = bannerTypeId;
       this.bannerTypeName = bannerTypeName;
       this.descriptions = descriptions;
       this.bannerTypePriority = bannerTypePriority;
       this.bannerTypeStatus = bannerTypeStatus;
       this.banners = banners;
    }
   
    public int getBannerTypeId() {
        return this.bannerTypeId;
    }
    
    public void setBannerTypeId(int bannerTypeId) {
        this.bannerTypeId = bannerTypeId;
    }
    public String getBannerTypeName() {
        return this.bannerTypeName;
    }
    
    public void setBannerTypeName(String bannerTypeName) {
        this.bannerTypeName = bannerTypeName;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public Integer getBannerTypePriority() {
        return this.bannerTypePriority;
    }
    
    public void setBannerTypePriority(Integer bannerTypePriority) {
        this.bannerTypePriority = bannerTypePriority;
    }
    public Boolean getBannerTypeStatus() {
        return this.bannerTypeStatus;
    }
    
    public void setBannerTypeStatus(Boolean bannerTypeStatus) {
        this.bannerTypeStatus = bannerTypeStatus;
    }
    public Set getBanners() {
        return this.banners;
    }
    
    public void setBanners(Set banners) {
        this.banners = banners;
    }




}


