package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Brands generated by hbm2java
 */
public class Brands  implements java.io.Serializable {


     private int brandId;
     private String brandName;
     private String brandImage;
     private Set productses = new HashSet(0);

    public Brands() {
    }

	
    public Brands(int brandId) {
        this.brandId = brandId;
    }
    public Brands(int brandId, String brandName, String brandImage, Set productses) {
       this.brandId = brandId;
       this.brandName = brandName;
       this.brandImage = brandImage;
       this.productses = productses;
    }
   
    public int getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public String getBrandImage() {
        return this.brandImage;
    }
    
    public void setBrandImage(String brandImage) {
        this.brandImage = brandImage;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


