package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int catId;
     private String catName;
     private Integer catPriority;
     private String catDescription;
     private Integer parentId;
     private Boolean catStatus;
     private Set productses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int catId, String catName) {
        this.catId = catId;
        this.catName = catName;
    }
    public Categories(int catId, String catName, Integer catPriority, String catDescription, Integer parentId, Boolean catStatus, Set productses) {
       this.catId = catId;
       this.catName = catName;
       this.catPriority = catPriority;
       this.catDescription = catDescription;
       this.parentId = parentId;
       this.catStatus = catStatus;
       this.productses = productses;
    }
   
    public int getCatId() {
        return this.catId;
    }
    
    public void setCatId(int catId) {
        this.catId = catId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public Integer getCatPriority() {
        return this.catPriority;
    }
    
    public void setCatPriority(Integer catPriority) {
        this.catPriority = catPriority;
    }
    public String getCatDescription() {
        return this.catDescription;
    }
    
    public void setCatDescription(String catDescription) {
        this.catDescription = catDescription;
    }
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
    public Boolean getCatStatus() {
        return this.catStatus;
    }
    
    public void setCatStatus(Boolean catStatus) {
        this.catStatus = catStatus;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


