package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Citys generated by hbm2java
 */
public class Citys  implements java.io.Serializable {


     private int cityId;
     private String cityName;
     private Boolean cityStatus;
     private Set storeses = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set userses = new HashSet(0);

    public Citys() {
    }

	
    public Citys(int cityId) {
        this.cityId = cityId;
    }
    public Citys(int cityId, String cityName, Boolean cityStatus, Set storeses, Set orderses, Set userses) {
       this.cityId = cityId;
       this.cityName = cityName;
       this.cityStatus = cityStatus;
       this.storeses = storeses;
       this.orderses = orderses;
       this.userses = userses;
    }
   
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Boolean getCityStatus() {
        return this.cityStatus;
    }
    
    public void setCityStatus(Boolean cityStatus) {
        this.cityStatus = cityStatus;
    }
    public Set getStoreses() {
        return this.storeses;
    }
    
    public void setStoreses(Set storeses) {
        this.storeses = storeses;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


