package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private int commentId;
     private Products products;
     private String email;
     private String userName;
     private Integer phoneNumber;
     private Date created;
     private String commentContent;
     private Integer parenId;
     private Integer starts;
     private Boolean commentStatus;

    public Comments() {
    }

	
    public Comments(int commentId) {
        this.commentId = commentId;
    }
    public Comments(int commentId, Products products, String email, String userName, Integer phoneNumber, Date created, String commentContent, Integer parenId, Integer starts, Boolean commentStatus) {
       this.commentId = commentId;
       this.products = products;
       this.email = email;
       this.userName = userName;
       this.phoneNumber = phoneNumber;
       this.created = created;
       this.commentContent = commentContent;
       this.parenId = parenId;
       this.starts = starts;
       this.commentStatus = commentStatus;
    }
   
    public int getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(int commentId) {
        this.commentId = commentId;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Integer getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
    public Integer getParenId() {
        return this.parenId;
    }
    
    public void setParenId(Integer parenId) {
        this.parenId = parenId;
    }
    public Integer getStarts() {
        return this.starts;
    }
    
    public void setStarts(Integer starts) {
        this.starts = starts;
    }
    public Boolean getCommentStatus() {
        return this.commentStatus;
    }
    
    public void setCommentStatus(Boolean commentStatus) {
        this.commentStatus = commentStatus;
    }




}


