package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private int feedbackId;
     private String fullName;
     private String email;
     private Integer phoneNumber;
     private Date created;
     private String fbcontents;
     private Boolean fbstatus;

    public Feedback() {
    }

	
    public Feedback(int feedbackId) {
        this.feedbackId = feedbackId;
    }
    public Feedback(int feedbackId, String fullName, String email, Integer phoneNumber, Date created, String fbcontents, Boolean fbstatus) {
       this.feedbackId = feedbackId;
       this.fullName = fullName;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.created = created;
       this.fbcontents = fbcontents;
       this.fbstatus = fbstatus;
    }
   
    public int getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(int feedbackId) {
        this.feedbackId = feedbackId;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public String getFbcontents() {
        return this.fbcontents;
    }
    
    public void setFbcontents(String fbcontents) {
        this.fbcontents = fbcontents;
    }
    public Boolean getFbstatus() {
        return this.fbstatus;
    }
    
    public void setFbstatus(Boolean fbstatus) {
        this.fbstatus = fbstatus;
    }




}


