package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Gift generated by hbm2java
 */
public class Gift  implements java.io.Serializable {


     private int giftId;
     @NotEmpty(message = "Mã quà tặng không được để trống..")
     private String giftCode;
     @NotEmpty(message = "Tên không được để trống...")
     private String giftName;
     private Date created;
     private String giftValue;
     private Set giftProducts = new HashSet(0);

    public Gift() {
    }

	
    public Gift(int giftId) {
        this.giftId = giftId;
    }
    public Gift(int giftId, String giftCode, String giftName, Date created, String giftValue, Set giftProducts) {
       this.giftId = giftId;
       this.giftCode = giftCode;
       this.giftName = giftName;
       this.created = created;
       this.giftValue = giftValue;
       this.giftProducts = giftProducts;
    }
   
    public int getGiftId() {
        return this.giftId;
    }
    
    public void setGiftId(int giftId) {
        this.giftId = giftId;
    }
    public String getGiftCode() {
        return this.giftCode;
    }
    
    public void setGiftCode(String giftCode) {
        this.giftCode = giftCode;
    }
    public String getGiftName() {
        return this.giftName;
    }
    
    public void setGiftName(String giftName) {
        this.giftName = giftName;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public String getGiftValue() {
        return this.giftValue;
    }
    
    public void setGiftValue(String giftValue) {
        this.giftValue = giftValue;
    }
    public Set getGiftProducts() {
        return this.giftProducts;
    }
    
    public void setGiftProducts(Set giftProducts) {
        this.giftProducts = giftProducts;
    }




}


