package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private int orderDeatailId;
     private Orders orders;
     private Products products;
     private Integer quantity;
     private float amount;

    public OrderDetail() {
    }

	
    public OrderDetail(int orderDeatailId) {
        this.orderDeatailId = orderDeatailId;
    }
    public OrderDetail(int orderDeatailId, Orders orders, Products products, Integer quantity, float amount) {
       this.orderDeatailId = orderDeatailId;
       this.orders = orders;
       this.products = products;
       this.quantity = quantity;
       this.amount = amount;
    }
   
    public int getOrderDeatailId() {
        return this.orderDeatailId;
    }
    
    public void setOrderDeatailId(int orderDeatailId) {
        this.orderDeatailId = orderDeatailId;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }




}


