package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Parameter generated by hbm2java
 */
public class Parameter  implements java.io.Serializable {


     private int paramId;
     private String paramName;
     private Boolean paramStatus;
     private Set productParameters = new HashSet(0);

    public Parameter() {
    }

	
    public Parameter(int paramId) {
        this.paramId = paramId;
    }
    public Parameter(int paramId, String paramName, Boolean paramStatus, Set productParameters) {
       this.paramId = paramId;
       this.paramName = paramName;
       this.paramStatus = paramStatus;
       this.productParameters = productParameters;
    }
   
    public int getParamId() {
        return this.paramId;
    }
    
    public void setParamId(int paramId) {
        this.paramId = paramId;
    }
    public String getParamName() {
        return this.paramName;
    }
    
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }
    public Boolean getParamStatus() {
        return this.paramStatus;
    }
    
    public void setParamStatus(Boolean paramStatus) {
        this.paramStatus = paramStatus;
    }
    public Set getProductParameters() {
        return this.productParameters;
    }
    
    public void setProductParameters(Set productParameters) {
        this.productParameters = productParameters;
    }




}


