package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * PolicyStore generated by hbm2java
 */
public class PolicyStore  implements java.io.Serializable {


     private int policyStoreId;
     private TypePolicyStore typePolicyStore;
     private String psname;
     private String pscontent;
     private Boolean psstatus;

    public PolicyStore() {
    }

	
    public PolicyStore(int policyStoreId, String psname) {
        this.policyStoreId = policyStoreId;
        this.psname = psname;
    }
    public PolicyStore(int policyStoreId, TypePolicyStore typePolicyStore, String psname, String pscontent, Boolean psstatus) {
       this.policyStoreId = policyStoreId;
       this.typePolicyStore = typePolicyStore;
       this.psname = psname;
       this.pscontent = pscontent;
       this.psstatus = psstatus;
    }
   
    public int getPolicyStoreId() {
        return this.policyStoreId;
    }
    
    public void setPolicyStoreId(int policyStoreId) {
        this.policyStoreId = policyStoreId;
    }
    public TypePolicyStore getTypePolicyStore() {
        return this.typePolicyStore;
    }
    
    public void setTypePolicyStore(TypePolicyStore typePolicyStore) {
        this.typePolicyStore = typePolicyStore;
    }
    public String getPsname() {
        return this.psname;
    }
    
    public void setPsname(String psname) {
        this.psname = psname;
    }
    public String getPscontent() {
        return this.pscontent;
    }
    
    public void setPscontent(String pscontent) {
        this.pscontent = pscontent;
    }
    public Boolean getPsstatus() {
        return this.psstatus;
    }
    
    public void setPsstatus(Boolean psstatus) {
        this.psstatus = psstatus;
    }




}


