package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Policy generated by hbm2java
 */
public class Policy  implements java.io.Serializable {


     private int policyId;
     private String policyName;
     private Boolean policyStatus;
     private Integer policyPriority;
     private Set productPolicies = new HashSet(0);

    public Policy() {
    }

	
    public Policy(int policyId) {
        this.policyId = policyId;
    }
    public Policy(int policyId, String policyName, Boolean policyStatus, Integer policyPriority, Set productPolicies) {
       this.policyId = policyId;
       this.policyName = policyName;
       this.policyStatus = policyStatus;
       this.policyPriority = policyPriority;
       this.productPolicies = productPolicies;
    }
   
    public int getPolicyId() {
        return this.policyId;
    }
    
    public void setPolicyId(int policyId) {
        this.policyId = policyId;
    }
    public String getPolicyName() {
        return this.policyName;
    }
    
    public void setPolicyName(String policyName) {
        this.policyName = policyName;
    }
    public Boolean getPolicyStatus() {
        return this.policyStatus;
    }
    
    public void setPolicyStatus(Boolean policyStatus) {
        this.policyStatus = policyStatus;
    }
    public Integer getPolicyPriority() {
        return this.policyPriority;
    }
    
    public void setPolicyPriority(Integer policyPriority) {
        this.policyPriority = policyPriority;
    }
    public Set getProductPolicies() {
        return this.productPolicies;
    }
    
    public void setProductPolicies(Set productPolicies) {
        this.productPolicies = productPolicies;
    }




}


