package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int productId;
     private Brands brands;
     private Categories categories;
     private String productCode;
     private String productName;
     private String title;
     private String productDescription;
     private Boolean productStatus;
     private Integer discount;
     private float price;
     private String created;
     private String productImage;
     private Integer productView;
     private Integer productHot;
     private Set productParameters = new HashSet(0);
     private Set productPolicies = new HashSet(0);
     private Set orderDetails = new HashSet(0);
     private Set giftProducts = new HashSet(0);
     private Set commentses = new HashSet(0);
     private Set imageses = new HashSet(0);

    public Products() {
    }

	
    public Products(int productId, String productName) {
        this.productId = productId;
        this.productName = productName;
    }
    public Products(int productId) {
        this.productId = productId;
        
    }
    public Products(int productId, Brands brands, Categories categories, String productCode, String productName, String title, String productDescription, Boolean productStatus, Integer discount, float price, String created, String productImage, Integer productView, Integer productHot, Set productParameters, Set productPolicies, Set orderDetails, Set giftProducts, Set commentses, Set imageses) {
       this.productId = productId;
       this.brands = brands;
       this.categories = categories;
       this.productCode = productCode;
       this.productName = productName;
       this.title = title;
       this.productDescription = productDescription;
       this.productStatus = productStatus;
       this.discount = discount;
       this.price = price;
       this.created = created;
       this.productImage = productImage;
       this.productView = productView;
       this.productHot = productHot;
       this.productParameters = productParameters;
       this.productPolicies = productPolicies;
       this.orderDetails = orderDetails;
       this.giftProducts = giftProducts;
       this.commentses = commentses;
       this.imageses = imageses;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public Boolean getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(Boolean productStatus) {
        this.productStatus = productStatus;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getCreated() {
        return this.created;
    }
    
    public void setCreated(String created) {
        this.created = created;
    }
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }
    public Integer getProductView() {
        return this.productView;
    }
    
    public void setProductView(Integer productView) {
        this.productView = productView;
    }
    public Integer getProductHot() {
        return this.productHot;
    }
    
    public void setProductHot(Integer productHot) {
        this.productHot = productHot;
    }
    public Set getProductParameters() {
        return this.productParameters;
    }
    
    public void setProductParameters(Set productParameters) {
        this.productParameters = productParameters;
    }
    public Set getProductPolicies() {
        return this.productPolicies;
    }
    
    public void setProductPolicies(Set productPolicies) {
        this.productPolicies = productPolicies;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }
    public Set getGiftProducts() {
        return this.giftProducts;
    }
    
    public void setGiftProducts(Set giftProducts) {
        this.giftProducts = giftProducts;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }




}


