package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1



/**
 * ProductPolicy generated by hbm2java
 */
public class ProductPolicy  implements java.io.Serializable {


     private int whishlistId;
     private Policy policy;
     private Products products;

    public ProductPolicy() {
    }

	
    public ProductPolicy(int whishlistId) {
        this.whishlistId = whishlistId;
    }
    public ProductPolicy(int whishlistId, Policy policy, Products products) {
       this.whishlistId = whishlistId;
       this.policy = policy;
       this.products = products;
    }
   
    public int getWhishlistId() {
        return this.whishlistId;
    }
    
    public void setWhishlistId(int whishlistId) {
        this.whishlistId = whishlistId;
    }
    public Policy getPolicy() {
        return this.policy;
    }
    
    public void setPolicy(Policy policy) {
        this.policy = policy;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }




}


