package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * ProductParameter generated by hbm2java
 */
public class ProductParameter  implements java.io.Serializable {


     private ProductParameterId id;
     private Parameter parameter;
     private Products products;
     private String proDetailValue;
     private Boolean proDetailStatus;

    public ProductParameter() {
    }

	
    public ProductParameter(ProductParameterId id, Parameter parameter, Products products) {
        this.id = id;
        this.parameter = parameter;
        this.products = products;
    }
    public ProductParameter(ProductParameterId id, Parameter parameter, Products products, String proDetailValue, Boolean proDetailStatus) {
       this.id = id;
       this.parameter = parameter;
       this.products = products;
       this.proDetailValue = proDetailValue;
       this.proDetailStatus = proDetailStatus;
    }
   
    public ProductParameterId getId() {
        return this.id;
    }
    
    public void setId(ProductParameterId id) {
        this.id = id;
    }
    public Parameter getParameter() {
        return this.parameter;
    }
    
    public void setParameter(Parameter parameter) {
        this.parameter = parameter;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getProDetailValue() {
        return this.proDetailValue;
    }
    
    public void setProDetailValue(String proDetailValue) {
        this.proDetailValue = proDetailValue;
    }
    public Boolean getProDetailStatus() {
        return this.proDetailStatus;
    }
    
    public void setProDetailStatus(Boolean proDetailStatus) {
        this.proDetailStatus = proDetailStatus;
    }




}


