package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Systems generated by hbm2java
 */
public class Systems  implements java.io.Serializable {


     private int systemId;
     private String systemContent;
     private String created;
     private Boolean systemStatus;

    public Systems() {
    }

	
    public Systems(int systemId) {
        this.systemId = systemId;
    }
    public Systems(int systemId, String systemContent, String created, Boolean systemStatus) {
       this.systemId = systemId;
       this.systemContent = systemContent;
       this.created = created;
       this.systemStatus = systemStatus;
    }
   
    public int getSystemId() {
        return this.systemId;
    }
    
    public void setSystemId(int systemId) {
        this.systemId = systemId;
    }
    public String getSystemContent() {
        return this.systemContent;
    }
    
    public void setSystemContent(String systemContent) {
        this.systemContent = systemContent;
    }
    public String getCreated() {
        return this.created;
    }
    
    public void setCreated(String created) {
        this.created = created;
    }
    public Boolean getSystemStatus() {
        return this.systemStatus;
    }
    
    public void setSystemStatus(Boolean systemStatus) {
        this.systemStatus = systemStatus;
    }




}


