package bkap.entity;
// Generated Oct 4, 2020 3:36:17 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String userId;
     private Citys citys;
     private String userName;
     private Integer userSex;
     private String userEmail;
     private String password;
     private String userAddress;
     private Integer permission;
     private Boolean userStatus;

    public Users() {
    }

	
    public Users(String userId) {
        this.userId = userId;
    }
    public Users(String userId, Citys citys, String userName, Integer userSex, String userEmail, String password, String userAddress, Integer permission, Boolean userStatus) {
       this.userId = userId;
       this.citys = citys;
       this.userName = userName;
       this.userSex = userSex;
       this.userEmail = userEmail;
       this.password = password;
       this.userAddress = userAddress;
       this.permission = permission;
       this.userStatus = userStatus;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Citys getCitys() {
        return this.citys;
    }
    
    public void setCitys(Citys citys) {
        this.citys = citys;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Integer getUserSex() {
        return this.userSex;
    }
    
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public Integer getPermission() {
        return this.permission;
    }
    
    public void setPermission(Integer permission) {
        this.permission = permission;
    }
    public Boolean getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Boolean userStatus) {
        this.userStatus = userStatus;
    }




}


